### PR TITLE
fix: Right clicking with a custom context menu open should open another context menu

### LINKED ISSUE #1525: Trying to open a context menu with a custom context menu already open does not work
**Description**

If you have a custom context menu already open (like on a table) and right click on something else that should create a custom context menu (like another table), the browser default context menu is opened instead.

**Steps to reproduce**

1. Open a table
2. Right click in the table
3. Custom context menu opens
4. Right click somewhere else in the table

**Expected results**

5. Custom context menu opens

**Actual results**

5. Browser default context menu opens

**Versions**

 - Web UI Version: 0.49.0
 - OS: PopOS 22.04 (Ubuntu-based)
 - Browser: Chromium 117

### PR DESCRIPTION
**Pull request by mattrunyon**
Fixes #1525 

This was bothering me while working on element plugins which should have a panel w/ the custom context menu enabled. Tested on Chrome/Firefox on Linux

### CODE REVIEW

**Comment by dsmmcken** [comment]
Please suggest a basic test plan we can use to manually check this, because this has proven tricky. I can do the windows testing.

We need to test manually on the full matrix:
- [ ] mac chrome
- [ ] mac firefox
- [ ] mac safari
- [ ] linux chrome
- [ ] linux firefox
- [ ] windows chrome
- [ ] windows edge
- [ ] windows firefox

**Comment by dsmmcken** [comment]
This introduces a new bug which prevents the native menu showing.

Right clicking on something that would be a native menu previously (like say you are trying to select text and copy text from a previously run command in the console) now it doesn't generate the native menu anymore, and further blocks all interactivity until another left click is performed. I assume we are generating like an empty menu with an overlay or something still when we shouldn't be.

Otherwise passes suggested manual testing on all Windows browsers.

**Comment by mattrunyon** [comment]
Good catch. It's actually an issue w/ just the console (native menu in other places like the maximize button or user settings button works fine).

We set/emit console clear and focus history as context actions, but they get filtered out by the util to turn them into menu items. Easy enough to add another check, but seems like a bug/unintended for those to be passed as context actions.

See https://github.com/deephaven/web-client-ui/blob/main/packages/console/src/Console.tsx#L878

**Comment by dsmmcken** [comment]
Also noted same behaviour in console history panel's search field.

**Comment by mattrunyon** [comment]
Ok should be fixed. I took a quick look back, but looks like those actions never registered properly since the initial fork of DHC. They've always been filtered out. Not sure why they're registered as context menu items really other than to setup the shortcut I guess.

**Review by mofojed — APPROVED** [review]
Verified looks good on Mac as well

**Review by mofojed — COMMENTED** [review]
Actually read Don's comments. Yeah the native menu still doesn't show up on the first right-click after showing our custom menu, unsure if that's something we should handle.
Also the context action items for clear/focus history were intended for keyboard shortcuts. Anything without a title is just a context action item that's triggered by keyboard and shouldn't appear in the menu.

**Comment by mattrunyon** [comment]
@mofojed Still good to merge this? I don't think we can handle showing the right-click after showing our custom menu. The event is getting re-emitted, but the browser doesn't seem to do anything with it. Probably because we listen for the event, but I'm guessing the native browser event can only be triggered by trusted/user-interaction events, not our re-emit.

**Comment by dsmmcken** [comment]
> the native menu still doesn't show up on the first right-click after showing our custom menu
It does on Chrome/Windows.

This is okay on the Windows side.

**Review by dsmmcken — APPROVED** [review]

**Pull request merged**
