### PR TITLE
refactor: Rename `ButtonGroup` to `SplitButtonGroup`

### PR DESCRIPTION
**Pull request by bmingles**
Renaming `ButtonGroup` to `SplitButtonGroup` to avoid naming collisions with Spectrum.

resolves https://github.com/deephaven/web-client-ui/issues/2015

BREAKING CHANGE: Renamed @deephaven/components `ButtonGroup` to `SplitButtonGroup`

### CODE REVIEW

**Comment by dsmmcken** [comment]
Shouldn't touch ButtonOld, I have no expectation of it having compatibility. I should just refactor it out entirely.

**Comment by dsmmcken** [comment]
Did you mean to do that on Button?

**Comment by bmingles** [comment]
@dsmmcken I'm planning to do this on Button as well. ButtonOld just happened to be the first attempt since it is used in the Styleguide where I was testing.

**Comment by mattrunyon** [comment]
What's the reason for the rename? Don't see anything here or in the ticket

**Comment by bmingles** [comment]
> What's the reason for the rename? Don't see anything here or in the ticket

It's to allow us to re-export Spectrum ButtonGroup. I updated the ticket description with details.

**Review by mofojed — APPROVED** [review]

**Review by mofojed — APPROVED** [review]

**Pull request merged**
