### PR TITLE
Add the package directory to each packages package.json

### PR DESCRIPTION
**Pull request by mofojed**
- Manually updated the repository information for each package.json to specify the directory that package is in
- Should make relative links work correctly when packages are published
- Partial #445 
Implemented to match https://docs.npmjs.com/cli/v8/configuring-npm/package-json#repository

### CODE REVIEW

**Comment by mofojed** [comment]
Kicked off an alpha build to test published links: https://github.com/deephaven/web-client-ui/actions/runs/1917076585

**Comment by mofojed** [comment]
Created PR to address this in `marky-markdown`: https://github.com/npm/marky-markdown/pull/455

Not sure it will actually be updated though, since that package hasn't been updated in a while. Seems odd that _nobody_ has tried to fix this before, and the workaround is to just provide absolute links.

**Review by spasovski — DISMISSED** [review]
Neat. Monorepo support.

**Review by spasovski — APPROVED** [review]
💯

**Pull request merged**
