### PR TITLE
fix: DH-14630: useDebouncedViewportSearch: memoization bug

### LINKED ISSUE #1272: DH-14630: useDebouncedViewportSearch - memoization bug
**Description**

The `useDebouncedViewportSearch` creates a memoized debounced search function. The memoization is currently getting updated on every render due to a dependency on viewportData. It should only update when table or applyFiltersAndRefresh change

**Steps to reproduce**

In ACL Editor user list, try searching for "jdoe" then clearing, then searching "jdoe" again.

**Expected results**

Search results should reflect the latest value in the search field

**Actual results**

It's easy to get in a state where results don't match the search

**Versions**

This is only being consumed in ACL code that has not yet been merged.
Branch: bmingles_DH-14630_acl-editor-components

### PR DESCRIPTION
**Pull request by bmingles**
Supports DH-14630

fixes #1272

### CODE REVIEW

**Review by mofojed — APPROVED** [review]

**Comment by vbabich** [comment]
Can we merge this after #1262?

**Review by mofojed — CHANGES_REQUESTED** [review]
Wait for Vlad's merge

**Comment by bmingles** [comment]
> #1262

@vbabich  Yes. Mind letting me know once it's merged?

**Comment by vbabich** [comment]
@bmingles #1262 merged

**Review by mofojed — APPROVED** [review]

**Pull request merged**
