### PR TITLE
fix: quick filter focus text doesn't match canvas text

### PR DESCRIPTION
**Pull request by dsmmcken**
resolves: #1472 

looks like tnum wasn't being inherited.

### CODE REVIEW

**Review by mofojed — CHANGES_REQUESTED** [review]
Weird that this is only a problem with updated Chrome/Playwright?

However, with this fix I'm now  seeing strange behaviour in Firefox:
font-issue-review-firefox
Chrome still shifts by a couple pixels, and can fix that by changing the top padding in `.iris-grid-input-field` to `5px`...
font-issue-review-chrome

**Comment by dsmmcken** [comment]
> Chrome still shifts by a couple pixels, and can fix that by changing the top padding in .iris-grid-input-field to 5px...

That massively mis-aligns it for me in chrome/win the opposite direction.

**Comment by dsmmcken** [comment]
I am guessing we are running up against platform limitations. I adjusted so it's right in chrome/firefox on windows, but I don't think we can get it perfect against the matrix of OS and browsers. Does it look reasonable to you on linux or is it way off still?

**Review by mofojed — COMMENTED** [review]
Looks perfect for me on Ubuntu in both Firefox and Chrome. Mac it shifts up/down by a pixel or two, but fonts look the same.

I think just rebase off the latest and update snapshots then this is good to go. Thanks!

**Review by mofojed — APPROVED** [review]

**Pull request merged**
